In [14]:
pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.12/dist-packages (40.11.1)

In [15]:
import pandas as pd
import random
from faker import Faker

fake = Faker()

num_patients = 10000

data = []

for i in range(1, num_patients + 1):
    patient = {
        "Patient_ID": f"P{i:05d}",
        "Age": random.randint(20, 80),
        "Gender": random.choice(["Male", "Female"]),
        "Blood_Pressure": random.randint(80, 180),
        "Sugar_Level": random.randint(70, 200),
        "Cholesterol": random.randint(150, 300),
        "Heart_Rate": random.randint(60, 120)
    }
    data.append(patient)

# Create DataFrame
df = pd.DataFrame(data)

# Show sample
print(df.head(10))

# Save to CSV
df.to_csv("patients_data_faker.csv", index=False)

print("Data generated using Faker and saved as patients_data_faker.csv")

  Patient_ID  Age  Gender  Blood_Pressure  Sugar_Level  Cholesterol  \
0     P00001   54    Male             137          104          156
1     P00002   62  Female              93          103          259
2     P00003   65    Male             110          189          218
3     P00004   34    Male             170          193          166
4     P00005   39    Male              85          110          283
5     P00006   58  Female             110          193          286
6     P00007   30  Female             164           87          206
7     P00008   80    Male             130          168          284
8     P00009   24    Male             101          101          262
9     P00010   20  Female             110           94          223

   Heart_Rate
0         116
1          75
2         119
3          75
4          62
5         112
6         113
7          86
8         115
9          74
Data generated using Faker and saved as patients_data_faker.csv

In [22]:
print("\n--- Detailed Analysis of Key Health Metrics ---")

metrics = ['Blood_Pressure', 'Sugar_Level', 'Cholesterol', 'Heart_Rate']

for metric in metrics:
    print(f"\nAnalysis for: {metric}")
    print("---------------------------------")
    print(df[metric].describe())

    # Further analysis by Gender
    print(f"\n{metric} distribution by Gender:")
    display(df.groupby('Gender', observed=False)[metric].describe())

    # Further analysis by Risk Level
    print(f"\n{metric} distribution by Risk Level:")
    display(df.groupby('Risk_Level', observed=False)[metric].describe())

--- Detailed Analysis of Key Health Metrics ---

Analysis for: Blood_Pressure
---------------------------------
count    10000.000000
mean       129.546400
std         29.091172
min         80.000000
25%        104.000000
50%        129.000000
75%        155.000000
max        180.000000
Name: Blood_Pressure, dtype: float64

Blood_Pressure distribution by Gender:

         count        mean        std   min    25%    50%    75%    max
Gender
Female  4988.0  129.127706  29.382140  80.0  103.0  129.0  155.0  180.0
Male    5012.0  129.963089  28.795566  80.0  105.0  130.0  154.0  180.0

Blood_Pressure distribution by Risk Level:

             count        mean        std   min    25%    50%    75%    max
Risk_Level
High        1198.0  157.236227  21.452832  80.0  147.0  164.0  172.0  180.0
Low         3942.0  113.014713  21.483317  80.0   95.0  111.0  127.0  160.0
Medium      4860.0  136.129835  28.279225  80.0  112.0  140.0  160.0  180.0

Analysis for: Sugar_Level
---------------------------------
count    10000.000000
mean       134.423200
std         37.731187
min         70.000000
25%        102.000000
50%        134.000000
75%        167.000000
max        200.000000
Name: Sugar_Level, dtype: float64

Sugar_Level distribution by Gender:

         count        mean        std   min    25%    50%    75%    max
Gender
Female  4988.0  134.475942  37.682877  70.0  102.0  133.0  167.0  200.0
Male    5012.0  134.370710  37.782891  70.0  101.0  134.0  166.0  200.0

Sugar_Level distribution by Risk Level:

             count        mean        std   min     25%    50%     75%    max
Risk_Level
High        1198.0  169.328047  30.750296  70.0  156.00  182.0  191.00  200.0
Low         3942.0  115.303399  28.703169  70.0   91.25  113.0  134.75  180.0
Medium      4860.0  141.327366  37.199650  70.0  110.00  147.0  173.00  200.0

Analysis for: Cholesterol
---------------------------------
count    10000.000000
mean       224.329700
std         43.501685
min        150.000000
25%        187.000000
50%        224.000000
75%        262.000000
max        300.000000
Name: Cholesterol, dtype: float64

Cholesterol distribution by Gender:

         count        mean        std    min    25%    50%    75%    max
Gender
Female  4988.0  223.607658  43.444973  150.0  186.0  223.0  261.0  300.0
Male    5012.0  225.048284  43.550502  150.0  188.0  225.0  263.0  300.0

Cholesterol distribution by Risk Level:

             count        mean        std    min    25%    50%    75%    max
Risk_Level
High        1198.0  260.909850  35.469948  150.0  238.0  272.0  289.0  300.0
Low         3942.0  202.860731  34.973323  150.0  174.0  199.0  225.0  280.0
Medium      4860.0  232.726337  42.636669  150.0  198.0  236.0  269.0  300.0

Analysis for: Heart_Rate
---------------------------------
count    10000.000000
mean        89.829400
std         17.621934
min         60.000000
25%         74.000000
50%         90.000000
75%        105.000000
max        120.000000
Name: Heart_Rate, dtype: float64

Heart_Rate distribution by Gender:

         count       mean        std   min   25%   50%    75%    max
Gender
Female  4988.0  89.694066  17.505249  60.0  75.0  90.0  104.0  120.0
Male    5012.0  89.964086  17.738019  60.0  74.0  90.0  105.0  120.0

Heart_Rate distribution by Risk Level:

             count       mean        std   min    25%   50%    75%    max
Risk_Level
High        1198.0  90.085142  17.896839  60.0  74.25  90.0  105.0  120.0
Low         3942.0  89.595383  17.641512  60.0  74.00  90.0  105.0  120.0
Medium      4860.0  89.956173  17.539053  60.0  75.00  90.0  105.0  120.0

In [19]:
# Convert 'Gender' to categorical type for efficiency and consistency
df['Gender'] = df['Gender'].astype('category')

In [20]:
# Define risk thresholds
bp_high_threshold = 160
bp_medium_threshold = 130
sugar_high_threshold = 180
sugar_medium_threshold = 140
cholesterol_high_threshold = 280
cholesterol_medium_threshold = 220

def classify_risk(row):
    risk_factors = 0
    # Check Blood Pressure
    if row['Blood_Pressure'] > bp_high_threshold:
        risk_factors += 2 # High risk factor
    elif row['Blood_Pressure'] > bp_medium_threshold:
        risk_factors += 1 # Medium risk factor

    # Check Sugar Level
    if row['Sugar_Level'] > sugar_high_threshold:
        risk_factors += 2
    elif row['Sugar_Level'] > sugar_medium_threshold:
        risk_factors += 1

    # Check Cholesterol
    if row['Cholesterol'] > cholesterol_high_threshold:
        risk_factors += 2
    elif row['Cholesterol'] > cholesterol_medium_threshold:
        risk_factors += 1

    if risk_factors >= 4:
        return 'High'
    elif risk_factors >= 2:
        return 'Medium'
    else:
        return 'Low'

# Apply the classification function to create the 'Risk_Level' column
df['Risk_Level'] = df.apply(classify_risk, axis=1)

# Convert 'Risk_Level' to categorical type for efficiency
df['Risk_Level'] = df['Risk_Level'].astype('category')

In [21]:
print("DataFrame with Risk_Level column:")
display(df.head())

DataFrame with Risk_Level column:

,Patient_ID,Age,Gender,Blood_Pressure,Sugar_Level,Cholesterol,Heart_Rate,Risk_Level
0,P00001,54,Male,137,104,156,116,Low
1,P00002,62,Female,93,103,259,75,Low
2,P00003,65,Male,110,189,218,119,Medium
3,P00004,34,Male,170,193,166,75,High
4,P00005,39,Male,85,110,283,62,Medium